# Reactive Server — Banned IPs
# Change the values below and restart the server or core using /reactive reload
# IP addresses listed here are banned from the server.

# Example:
# [192.168.1.100]
# expiresOn = "2026-05-02 13:35:44 +0000"
# source = "Admin"
# reason = "DDoS attack"

