blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/rizer001/Reactive/discussions/new?category=feature-requests
    about: Suggest an idea for Reactive
  - name: Exploit Report
    url: https://github.com/rizer001/Reactive/issues/new
    about: |
      Since GitHub does not allow private issues, exploit reports are currently handled through GitHub Issues.
      Please use the bug report template and mark it as sensitive.
  - name: Reactive Discord
    url: https://github.com/rizer001/Reactive
    about: Join our community for help and discussion!
